spring:
  application:
    name: raman

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yml

  datasource:
    url: jdbc:postgresql://localhost:6160/Spotify
    username: postgres
    password: Raman@123
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000



spotify:
  client:
    clientId: 27d1c4fc4da2455b83152d028458850a
    clientSecret: 5e4e5488585c4ef29464a58c7550a385





