spring:
  application:
    name: raman

  liquibase:
    enable: false
    change-log: classpath:db/changelog/db.changelog-master.yaml

  datasource:
    url: jdbc:postgresql://localhost:6160/mydatabase
    username: myusername
    password: mypassword
    driver-class-name: org.postgresql.Driver


spotify:
  client:
    clientId: 27d1c4fc4da2455b83152d028458850a
    clientSecret: 5e4e5488585c4ef29464a58c7550a385





